### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by titanous**
- Golang -> Go (golang.org is the hostname of the website, Go is the name of the language)
- Ensure that all URLs are HTTPS

### CODE REVIEW

**Comment by mimoo** [comment]
Hey!

Thanks for the PR I appreciate :)

Can you just revert back Go to golang? This was done on purpose as Go is already a well-known boardgame.

**Comment by titanous** [comment]
> Can you just revert Go back to Golang? This was done on purpose as Go is already a well-known boardgame.

Yeah, I can do that later today if you really want. I don't find this particularly confusing, Ruby (ruby-lang.org) is also a well-known type of gem, Python is a well-known snake genus, C is a letter in the English alphabet, Rust (rust-lang.org) is an iron oxide, etc.

By definition if you want to use an existing word to name your programming language, it is already used for other things. And `*lang.org` is a very common ending for programming language domain names.

**Comment by mimoo** [comment]
As a Go player it confuses me often enough to annoy me ^^ (I'm extremely biased on this topic though)

**Comment by titanous** [comment]
I've updated this PR to remove that commit.

**Comment by mimoo** [comment]
Thanks! merged

**Pull request merged**
